#!/usr/bin/env bash
#manages file
case "$1" in
	start)
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo 'manage_my_process started'
		;;
	stop)
		echo 'manage_my_process stopped'
		pkill -f manage_my_process
		rm -f /var/run/my_process.pid
		;;
	restart)
		pkill -f manage_my_process
		rm -f /var/run/my_process.pid
		./manage_my_process &
                echo $! > /var/run/my_process.pid
		echo 'manage_my_process restarted'
		;;
	*)
		echo 'Usage: manage_my_process {start|stop|restart}'
		;;
esac
